name: auto-merge

on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - package.json
      - yarn.lock

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          command: squash and merge
          github-token: ${{ secrets.WESBAKER_TOKEN }}
          target: minor
